/* A collected-evidence view; it never supplies conclusions or undiscovered material. */
(function(global){
'use strict';const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
function render(root,state,pack,{showNotes=false}={}){if(!root)return;const entries=SharedInventory.entries(state,pack).filter(i=>i.isEvidence),signature=JSON.stringify([entries,showNotes?state.notes:null]);if(root._caseSignature===signature)return;root._caseSignature=signature;
const selected=root._compared||new Set();root._compared=selected;for(const id of selected)if(!entries.some(i=>i.id===id))selected.delete(id);
const expanded=new Set([...root.querySelectorAll('details[open]')].map(e=>e.dataset.id));root.replaceChildren(node('h2','Collected evidence'));const help=node('p','Open a document to reread it, or select two pieces of evidence to compare. Connections and conclusions are yours to make.');root.append(help);const listing=node('div'),comparison=node('div');comparison.setAttribute('aria-label','Evidence comparison');comparison.style.cssText='display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:16px';root.append(listing,comparison);
function compare(){comparison.replaceChildren();for(const item of entries.filter(i=>selected.has(i.id))){const card=node('article');card.style.cssText='background:#241e2d;border:1px solid #aa9257;padding:18px;color:#faf5e7';const text=node('p',item.text);text.style.cssText='white-space:pre-wrap;line-height:1.6';card.append(node('h3',item.name),text);comparison.append(card);}for(const check of listing.querySelectorAll('input'))check.disabled=selected.size>=2&&!check.checked;}
if(!entries.length)listing.append(node('p','No murder evidence collected yet. Search the estate and bring your discoveries here.'));
for(const item of entries){const row=node('div');row.style.cssText='padding:12px;margin:10px 0;border:1px solid #8b774b;border-radius:6px';const label=node('label'),check=node('input');label.style.cssText='display:flex;align-items:center;gap:8px;margin-bottom:10px';check.style.cssText='width:auto;margin:0;flex:none';check.type='checkbox';check.checked=selected.has(item.id);check.setAttribute('aria-label','Compare '+item.name);check.onchange=()=>{if(check.checked)selected.add(item.id);else selected.delete(item.id);compare();};label.append(check,node('span',' Compare'));const detail=node('details');detail.dataset.id=item.id;detail.open=expanded.has(item.id);const text=node('p',item.text);text.style.cssText='white-space:pre-wrap;line-height:1.6';detail.append(node('summary',item.name),text);row.append(label,detail);listing.append(row);}compare();
if(showNotes){root.append(node('h3','Group observations'));const notes=Object.values(state.notes||{});if(!notes.length)root.append(node('p','No observations pinned yet. Add them at the Case Board on the TV.'));for(const note of notes){const text=node('p',note.text);text.style.whiteSpace='pre-wrap';root.append(text);}}
}
global.CaseBoard={render};
})(window);
