'use strict';
let ROOMS=[];
const $=id=>document.getElementById(id),gameId=new URLSearchParams(location.search).get('id');let tv={},tvRef,storyMap=null;
firebase.initializeApp({apiKey:'AIzaSyApHrYubqWrR4m0ihdpq6Ym40jv4HTQ5i0',authDomain:'thoreson-estate.firebaseapp.com',databaseURL:'https://thoreson-estate-default-rtdb.firebaseio.com',projectId:'thoreson-estate'});
const db=firebase.database();const tell=text=>$('notice').textContent=text;
let roomStep=null,roomSteps=[];
function roomLocked(id){const gate=storyMap?.access?.[id];if(!gate)return false;if(!gate.unlockAtStep)return true;const unlock=roomSteps.findIndex(s=>s.id===gate.unlockAtStep),current=roomSteps.findIndex(s=>s.id===roomStep);return unlock<0||current<unlock;}
function roomState(){return roomLocked(tv.currentRoom)?{...tv,currentRoom:null}:tv;}
function setRoomStep(id,steps){roomStep=id;roomSteps=steps;window.roomInteractionUI?.setStep(id);render();}
const nameOf=room=>typeof tv.roomNames?.[room[0]]==='string'?tv.roomNames[room[0]]:room[1];
function element(tag,text){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node;}
async function save(values){try{await tvRef.update(values);tell('');return true;}catch(e){tell('Could not save. Check your connection and try again.');return false;}}
const focusPanels=[$('mapDialog'),$('boardDialog'),$('inventoryDialog')];
for(const panel of focusPanels)document.querySelector('.focus').append(panel);
function closeFocusPanels(){for(const panel of focusPanels)panel.close();document.querySelectorAll('.focus > *').forEach(node=>{node.inert=false;});window.roomInteractionUI?.setFocus('room');}
function openFocusPanel(id){window.pauseActiveScene?.();closeFocusPanels();const panel=$(id);panel.hidden=false;document.querySelectorAll('.focus > *').forEach(node=>{node.inert=node!==panel;});panel.show();window.roomInteractionUI?.setFocus(id==='interactionDialog'?'object':'overview');}
function openMap(){openFocusPanel('mapDialog');}
$('openMap').onclick=openMap;$('showEstate').onclick=openMap;$('openBoard').onclick=()=>openFocusPanel('inventoryDialog');
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&focusPanels.some(p=>p.open)){e.preventDefault();const id=$('mapDialog').open?'openMap':'openBoard';closeFocusPanels();$(id).focus();}});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{closeFocusPanels();$(b.dataset.close==='mapDialog'?'openMap':'openBoard').focus();});
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){tell('Fullscreen is unavailable in this browser. Maximize this window instead.');}};
document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'Exit fullscreen':'Fullscreen';});
function stopVideo(){$('storyVideo').pause();$('storyVideo').hidden=true;$('roomView').hidden=false;renderFocus();}

function renderFocus(){const room=ROOMS.find(r=>r[0]===roomState().currentRoom);$('currentRoom').textContent=room?nameOf(room):'Explore the map';const marker=$('miniMarker');marker.style.display=room?'block':'none';if(room)Object.assign(marker.style,{left:room[2]+'%',top:room[3]+'%',width:room[4]+'%',height:room[5]+'%'});if(!$('storyVideo').hidden)return;
$('focusTitle').textContent=room?nameOf(room):'Welcome';$('focusCaption').textContent=room?'You are exploring '+nameOf(room)+'. Open the map to move to another room.':'Select a room on the map to explore together.';
const art=$('roomArt'),view=room&&storyMap.roomViews?.[room[0]];art.setAttribute('aria-label',view?.alt||(room?nameOf(room):'Full map'));
art.style.backgroundImage='url('+JSON.stringify(view?.image||storyMap?.image||"")+')';
if(view){Object.assign(art.style,{width:'100%',height:'100%',backgroundSize:'contain',backgroundPosition:'center'});return;}
if(room){const [, ,x,y,w,h]=room;const container=$('roomView');const ratio=(w/h)*(storyMap.width/storyMap.height);let width=container.clientWidth,height=width/ratio;if(height>container.clientHeight){height=container.clientHeight;width=height*ratio;}Object.assign(art.style,{width:width+'px',height:height+'px',backgroundSize:(10000/w)+'% '+(10000/h)+'%',backgroundPosition:(x/(100-w)*100)+'% '+(y/(100-h)*100)+'%'});}else Object.assign(art.style,{width:'100%',height:'100%',backgroundSize:'contain',backgroundPosition:'center'});}
function render(){renderFocus();if(window.roomInteractionUI)roomInteractionUI.update(roomState());$('roomButtons').replaceChildren();for(const room of ROOMS){const b=element('button');b.type='button';b.append(element('span',nameOf(room)));b.setAttribute('aria-label','Enter '+nameOf(room));b.classList.toggle('selected',room[0]===tv.currentRoom);Object.assign(b.style,{left:room[2]+'%',top:room[3]+'%',width:room[4]+'%',height:room[5]+'%'});const gate=storyMap.access?.[room[0]];if(roomLocked(room[0])){b.classList.add('room-locked');b.setAttribute('aria-description',gate.title);for(let i=0;i<2;i++){const tape=element('em',gate.tapeLabel);tape.className='room-tape tape-'+i;tape.setAttribute('aria-hidden','true');b.append(tape);}}b.onclick=async()=>{if(roomLocked(room[0])){roomInteractionUI.showNotice(storyMap.access[room[0]],openMap);return;}b.disabled=true;if(await save({currentRoom:room[0]})){if(!$('flowScreen')||$('flowScreen').hidden)stopVideo();closeFocusPanels();$('openMap').focus();}b.disabled=false;};$('roomButtons').append(b);}
const notes=Object.entries(tv.notes || {});$('boardNotes').replaceChildren();if(!notes.length)$('boardNotes').append(element('p','The board is empty. Add what the group discovers.'));for(const [id,note] of notes){const card=element('article');card.className='note';card.append(element('div',note.text));const remove=element('button','Remove note');remove.onclick=async()=>{if(confirm('Remove this observation from the board?'))await save({['notes/'+id]:null});};card.append(remove);$('boardNotes').append(card);}}
$('nameRooms').onclick=()=>{$('nameFields').replaceChildren();for(const room of ROOMS){const label=element('label',room[1]);const input=element('input');input.name=room[0];input.value=nameOf(room);input.maxLength=40;input.required=true;label.append(input);$('nameFields').append(label);}$('roomNames').hidden=false;$('namesStatus').textContent='';$('roomNames').scrollIntoView({behavior:'smooth'});$('nameFields').querySelector('input').focus();};
$('cancelNames').onclick=()=>{$('roomNames').hidden=true;};
$('roomNames').onsubmit=async e=>{e.preventDefault();const values={};for(const input of $('nameFields').querySelectorAll('input')){if(!input.value.trim())return $('namesStatus').textContent='Every room needs a name.';values['roomNames/'+input.name]=input.value.trim();}const b=e.submitter;b.disabled=true;if(await save(values)){$('roomNames').hidden=true;$('nameRooms').focus();}else $('namesStatus').textContent='Names were not saved. Please try again.';b.disabled=false;};
$('noteForm').onsubmit=async e=>{e.preventDefault();const text=$('noteText').value.trim();if(!text)return;if(Object.keys(tv.notes||{}).length>=80)return tell('The board holds 80 notes. Remove a note before adding another.');const b=e.submitter;b.disabled=true;const id=db.ref().push().key;if(await save({['notes/'+id]:{text,createdAt:Date.now()}}))$('noteText').value='';b.disabled=false;};
new ResizeObserver(renderFocus).observe($('roomView'));
firebase.auth().onAuthStateChanged(async user=>{if(!user||user.isAnonymous){tell('Sign in on the host page, then launch the game again.');return;}if(!gameId||/[.#$\[\]/]/.test(gameId)){tell('Open this screen using Launch Game on your host page.');return;}try{const game=(await db.ref('games/'+gameId).once('value')).val();if(!game||game.createdBy!==user.uid){tell('This TV screen is available to the party host.');return;}const pack=await StoryRuntime.load(game.storyId);storyMap=pack.map||{rooms:[],width:1,height:1,image:''};ROOMS=storyMap.rooms;document.getElementById('openMap').hidden=!ROOMS.length;document.getElementById('showEstate').hidden=!ROOMS.length;document.querySelectorAll('.map-wrap>img,.mini-image img').forEach(img=>{img.src=storyMap.image;img.alt=pack.title+' map';});$('roomArt').style.backgroundImage='url('+JSON.stringify(storyMap.image)+')';document.querySelector('#mapDialog h2').textContent=pack.title;$('hostLink').href='game.html?id='+encodeURIComponent(gameId);$('partyName').textContent=game.partyName||game.storyName||'Your story';$('partyStatus').textContent=game.status==='active'?'GAME IN PROGRESS':'PREVIEW';$('stage').hidden=false;window.roomInteractionUI=RoomInteractions.mount({pack,mazeContext:{db,gameId,uid:user.uid,host:true,pack},getState:roomState,save,open:openFocusPanel,close:closeFocusPanels,panels:focusPanels});mountStoryFlow(db,gameId,pack);tvRef=db.ref('games/'+gameId+'/state/tv');tvRef.on('value',snap=>{tv=snap.val()||{};render();tell('');},()=>tell('Could not load the game screen. Refresh to reconnect.'));db.ref('games/'+gameId+'/status').on('value',snap=>{$('partyStatus').textContent=snap.val()==='active'?'GAME IN PROGRESS':'PREVIEW';});}catch(e){tell(e.message || 'Could not open the party. Refresh to try again.');}});
